

export const initialHotelsData = [
    {
        id:"0",
        image:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSLB7zfxFCFag7Pt9CHnH3wk61PILgDo5CCTxT01YjSmEKOVY6uskLp8qEnLi8sIsAAMBOWo4AGXHUavOeuWowkrR4u4QtSlryJKCwcR837ajLT906ZOcBhwQuomU453tC8azJe5SikPUleEkJhz-FmTQKa8frlxB7tir-_0V97PqF89QHvQfh5iNH/s16000/IMG_20220904_210330.jpg",
        name:"Haldiram",
        rating:4.4,
        time:"30-40",
        adress:"Residency Road | Ashok Nagar",
        ratings:"1.5k",
        cost_for_two:500,
        cuisines:"north Indian, South Indian, Fast food",
        isFavourite:false,
        menu:[
            {
                id: "101",
                name: "Paneer 65",
                price: 275,
                description: "A spicy and tangy starter made with deep-fried paneer cubes coated in a blend of aromatic spices.",
                rating: 4.1,
                ratings: 43,
                image: "https://www.tropicalcurryandgrill.com/wp-content/uploads/2020/12/Paneer-65-2048x1363.jpeg",
                veg: true,
                bestSeller: false,
                quantity: 1,
                selected: false,
            },
            {
                id: "102",
                name: "Chilly Chicken (Boneless)",
                price: 285,
                description: "Boneless chicken pieces cooked in a spicy and tangy sauce with bell peppers and onions.",
                rating: 4.3,
                ratings: 34,
                image: "https://img.food.boxspace.in/image/rbk_59c91a5172e56/xhdpi.jpg",
                veg: false,
                bestSeller: true,
                quantity: 1,
                selected: false,
            },
            {
                id: "103",
                name: "Spl Veg Biryani",
                price: 250,
                description: "A special vegetarian biryani made with fragrant basmati rice and a mix of fresh vegetables.",
                rating: 4.5,
                ratings: 56,
                image: "https://th.bing.com/th/id/OIP.iydKkwiqSiKvtTLuhZvwcQHaGL?rs=1&pid=ImgDetMain",
                veg: true,
                bestSeller: false,
                quantity: 1,
                selected: false,
            },
            {
                id: "104",
                name: "Chilly Paneer",
                price: 220,
                description: "Paneer cubes cooked with bell peppers and onions in a spicy and tangy sauce.",
                rating: 3.8,
                ratings: 22,
                image: "https://th.bing.com/th/id/OIP.FQRrRG-O9lWnySN8xlpTXAHaFj?rs=1&pid=ImgDetMain",
                veg: true,
                bestSeller: true,
                quantity: 1,
                selected: false,
            },
            {
                id: "105",
                name: "Chicken 65",
                price: 300,
                description: "A spicy, deep-fried chicken dish marinated with red chili paste and curry leaves.",
                rating: 4.5,
                ratings: 45,
                image: "https://1.bp.blogspot.com/-ik59wslvuU0/X5gsTeZBBNI/AAAAAAAAY9U/MiHe337A5lw98VGCcf1tolA7plTyENMHQCLcBGAsYHQ/s2048/chicken%2B65%2B10.JPG",
                veg: false,
                bestSeller: true,
                quantity: 1,
                selected: false,
            },
            {
                id: "201",
                name: "Chicken Fried Rice",
                price: 260,
                description: "Stir-fried rice with chicken pieces, vegetables, and a blend of Chinese sauces.",
                rating: 4.3,
                ratings: 34,
                image: "https://th.bing.com/th/id/OIP.EdtFdGsiPMUNRsxXORO6UwHaHa?rs=1&pid=ImgDetMain",
                veg: false,
                bestSeller: true,
                quantity: 1,
                selected: false,
            },
            {
                id: "202",
                name: "Egg Fried Rice",
                price: 220,
                description: "Stir-fried rice with scrambled eggs, vegetables, and a blend of Chinese sauces.",
                rating: 4.3,
                ratings: 52,
                image: "https://th.bing.com/th/id/OIP.NM1x5LEODmaXG585LmNZtwHaJQ?rs=1&pid=ImgDetMain",
                veg: false,
                bestSeller: false,
                quantity: 1,
                selected: false,
            },
            {
                id: "203",
                name: "Veg Fried Rice",
                price: 190,
                description: "Stir-fried rice with a mix of fresh vegetables and a blend of Chinese sauces.",
                rating: 4.6,
                ratings: 56,
                image: "https://www.kannammacooks.com/wp-content/uploads/schezwan-veg-fried-rice-1.jpg",
                veg: true,
                bestSeller: true,
                quantity: 1,
                selected: false,
            },
            {
                id: "204",
                name: "Jeera Rice",
                price: 195,
                description: "Basmati rice flavored with cumin seeds, cooked to perfection.",
                rating: 4.5,
                ratings: 48,
                image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/12/jeera-rice-recipe.jpg",
                veg: true,
                bestSeller: false,
                quantity: 1,
                selected: false,
            },
        ]
    },
  
  
  
    {
        id:"1",
        image:"https://th.bing.com/th?id=OIP.Db_Tb2HHRMChf0qMt56dUwHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
        name:"KFC",
        rating:4.2,
        time:"30-40",
        adress:"Richmond Town, Ashok Nagar ",
        ratings:"500",
        cost_for_two:450,
        cuisines:"north Indian, South Indian, Fast food",
        isFavourite:false,
        menu:[
    
            {
                "id": "101",
                "name": "Original Recipe Chicken",
                "price": 275,
                "description": "KFC's signature dish, featuring hand-breaded and fried chicken seasoned with Colonel Sanders' secret blend of 11 herbs and spices. The chicken is juicy on the inside with a crispy, flavorful crust.",
                "rating": 4.1,
                "ratings": 43,
                "image": "https://th.bing.com/th/id/OIP.ZBaKV5J0Vq32slhmLiz7awHaFk?rs=1&pid=ImgDetMain",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "102",
                "name": "Extra Crispy Chicken",
                "price": 300,
                "description": "A crunchier version of KFC's chicken, this variety is double-breaded for extra crunch. It has a more intense, crispy texture while maintaining the juicy tenderness of the chicken inside.",
                "rating": 4.3,
                "ratings": 55,
                "image": "https://images.says.com/uploads/story_source/source_image/1134551/d80f.jpg",
                "veg": false,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "103",
                "name": "Hot & Spicy Chicken",
                "price": 320,
                "description": "For those who like a bit of heat, KFC's Hot & Spicy Chicken is marinated in a special blend of spicy seasonings and then fried to perfection. It offers a spicy kick without overwhelming the palate.",
                "rating": 4.2,
                "ratings": 49,
                "image": "https://th.bing.com/th/id/OIP.Z3eQjrFrVkvx8e49ozG3rwAAAA?rs=1&pid=ImgDetMain",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "104",
                "name": "Popcorn Chicken",
                "price": 150,
                "description": "Bite-sized pieces of chicken that are breaded and fried until golden and crispy. Popcorn Chicken is perfect for snacking or sharing and is often served with dipping sauces.",
                "rating": 4.4,
                "ratings": 60,
                "image": "https://th.bing.com/th/id/OSK.4eade51e988bbe47650ff0b85da9557e?w=474&h=474&o=6&rs=1&pid=ImgDetMain",
                "veg": false,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "105",
                "name": "Chicken Tenders",
                "price": 200,
                "description": "Tender, juicy strips of chicken breast that are breaded and fried. These are great for dipping and come with a choice of sauces. They offer a boneless alternative to traditional fried chicken.",
                "rating": 4.5,
                "ratings": 53,
                "image": "https://th.bing.com/th/id/R.bb8750e80994d87cd80e833b4eccd162?rik=TvUiquMreRMQGQ&riu=http%3a%2f%2ffarm8.staticflickr.com%2f7284%2f8747605385_ea988ca78c.jpg&ehk=QaEr0pbLjaW1OD%2bO%2fhGIR0Zikx%2bERyHnihinXicmPK4%3d&risl=&pid=ImgRaw&r=0",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "106",
                "name": "Zinger Burger",
                "price": 250,
                "description": "A spicy chicken fillet sandwich, the Zinger Burger features a fiery chicken breast fillet, crispy lettuce, and mayonnaise, all served on a toasted bun. It's a popular choice for those craving a spicy sandwich.",
                "rating": 4.6,
                "ratings": 67,
                "image": "https://globalprimenews.com/wp-content/uploads/2020/10/IMG-20201031-WA0004.jpg",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "107",
                "name": "KFC Famous Bowl",
                "price": 180,
                "description": "This comforting dish layers creamy mashed potatoes, sweet corn, and bite-sized pieces of crispy chicken, all topped with home-style gravy and shredded cheese. It's a hearty, all-in-one meal.",
                "rating": 4.3,
                "ratings": 45,
                "image": "https://imgix.bustle.com/uploads/image/2019/1/9/00449ad9-1d6b-434e-be78-ecabaefa129e-kfc-famous-bowls-3-limited-time-only-1.jpg?w=1200&h=630&q=70&fit=crop&crop=faces&fm=jpg",
                "veg": false,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "108",
                "name": "Potato Wedges",
                "price": 100,
                "description": "Thick-cut potato wedges seasoned with KFC's special blend of spices and fried until crispy on the outside and fluffy on the inside. They are a popular side dish and an alternative to traditional fries.",
                "rating": 4.2,
                "ratings": 38,
                "image": "https://th.bing.com/th/id/OSK.56dcfa373849e4437a32a80016795596?w=474&h=711&o=6&w=680&h=1020&rs=1&pid=ImgDetMain",
                "veg": true,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "109",
                "name": "Coleslaw",
                "price": 80,
                "description": "A refreshing side dish, KFC's coleslaw is made from freshly shredded cabbage, carrots, and onions, mixed with a tangy and slightly sweet mayonnaise-based dressing. It's a cool and crunchy complement to the fried chicken.",
                "rating": 4.0,
                "ratings": 34,
                "image": "https://www.shugarysweets.com/wp-content/uploads/2021/07/kfc-coleslaw-facebook-scaled.jpg",
                "veg": true,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            }
            
            

            
            
            
            
            
            
            

            
        ]
    },
    {
        id:"2",
        image:"https://media.marketrealist.com/brand-img/DJRFLbMHq/0x0/uploads/2019/11/McDonalds-overview.jpeg",
        name:"McDonald's",
        rating:4.3,
        time:"45-50",
        adress:"Residency Road, Shantinagar",
        ratings:"100",
        cost_for_two:430,
        cuisines:"north Indian, South Indian, Fast food",
        isFavourite:false,
        menu:[
            {
                "id": "201",
                "name": "Big Mac",
                "price": 375,
                "description": "Two all-beef patties, lettuce, cheese, pickles, onions, and special sauce on a sesame seed bun.",
                "rating": 4.5,
                "ratings": 150,
                "image": "https://th.bing.com/th/id/OIP.mMIbW6SCuWbkmnAfSIZs6AAAAA?rs=1&pid=ImgDetMain",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "202",
                "name": "French Fries",
                "price": 200,
                "description": "Crispy and golden, made from high-quality potatoes.",
                "rating": 4.7,
                "ratings": 200,
                "image": "https://th.bing.com/th/id/OIP.ugfVAAL56_KiiP-fm5-5eQAAAA?rs=1&pid=ImgDetMain",
                "veg": true,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "203",
                "name": "Chicken McNuggets",
                "price": 300,
                "description": "Tender, juicy chicken nuggets with a crispy coating, served with your choice of dipping sauces.",
                "rating": 4.3,
                "ratings": 120,
                "image": "https://i.iheart.com/v3/re/new_assets/5d405dbb27a18392a07a4c2c?ops=contain(1480,0)",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "204",
                "name": "Quarter Pounder with Cheese",
                "price": 350,
                "description": "A juicy quarter-pound beef patty with cheese, onions, pickles, mustard, and ketchup on a sesame seed bun.",
                "rating": 4.4,
                "ratings": 130,
                "image": "https://th.bing.com/th/id/OIP.FBoMbe7OlqFsKf7OLfh3-wHaFA?rs=1&pid=ImgDetMain",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "205",
                "name": "Filet-O-Fish",
                "price": 275,
                "description": "A breaded fish fillet topped with tartar sauce and a slice of cheese, served on a steamed bun.",
                "rating": 4.0,
                "ratings": 80,
                "image": "https://farm4.staticflickr.com/3509/3457876408_9a5f785cd6_b.jpg",
                "veg": false,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "206",
                "name": "Egg McMuffin",
                "price": 200,
                "description": "A freshly cracked egg, Canadian bacon, and melted cheese on a toasted English muffin.",
                "rating": 4.6,
                "ratings": 90,
                "image": "https://th.bing.com/th?id=OIP.a1W0JAktN31kvVfY0UIHEgHaFj&w=288&h=216&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "207",
                "name": "Happy Meal",
                "price": 250,
                "description": "Includes a choice of a main item (hamburger, cheeseburger, or Chicken McNuggets), a side, a drink, and a toy.",
                "rating": 4.2,
                "ratings": 110,
                "image": "https://vignette.wikia.nocookie.net/ronaldmcdonald/images/c/cf/Happy_Meal_2000s.jpg/revision/latest?cb=20150625062226",
                "veg": false,
                "bestSeller": true,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "208",
                "name": "McChicken",
                "price": 275,
                "description": "A breaded chicken patty with lettuce and mayonnaise, served on a toasted bun.",
                "rating": 4.3,
                "ratings": 105,
                "image": "https://mltwiersgrjj.i.optimole.com/UjSS7Fo-XP777vwU/w:416/h:416/q:90/https://menumcdo.com/wp-content/uploads/2021/04/210325-MCDO-MBO-MCCHICKEN.png",
                "veg": false,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            },
            {
                "id": "209",
                "name": "Apple Pie",
                "price": 100,
                "description": "A warm, flaky pie crust filled with sweet apple filling, baked to perfection.",
                "rating": 4.5,
                "ratings": 95,
                "image": "hhttps://media.marketrealist.com/brand-img/DJRFLbMHq/0x0/uploads/2019/11/McDonalds-overview.jpeg",
                "veg": true,
                "bestSeller": false,
                "quantity": 1,
                "selected": false
            }
        ]
        
    }
  ]